### ISSUE TITLE
warihash_connect_desktop-7b7bbb5-dirty.exe

### ISSUE THREAD

**Issue by kaykurokawa** [warigroup/warihash_connect_desktop#2]
Login problems on Windows 10 using warihash_connect_desktop-7b7bbb5-dirty.exe
```
Traceback (most recent call last):
  File "electrum\util.py", line 855, in run_with_except_hook
  File "threading.py", line 864, in run
  File "C:\Users\SKYWRA~1\AppData\Local\Temp\_MEI108762\electrum\plugins\warihash\qt.py", line 440, in start_session
    if not self.connect():
  File "C:\Users\SKYWRA~1\AppData\Local\Temp\_MEI108762\electrum\plugins\warihash\qt.py", line 216, in connect
    WARIHASH_CLIENT_CERTIFICATE, WARIHASH_CLIENT_KEY)
FileNotFoundError: [Errno 2] No such file or directory
 ```
Additional information
Electrum version: 3.3.4 
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] 
Operating system: Windows-10-10.0.17134 
Wallet type: standard 
Locale: en_US

**Comment by kaykurokawa** [comment]
No longer using this
