### ISSUE TITLE
alpha.warihash.com seems to be hardcoded somehow

### ISSUE THREAD

**Issue by kaykurokawa** [warigroup/warihash_connect_desktop#4]
I tried running connect desktop , in order to test dev.warihash.com .

I set up the Warihash Account settings to use dev.warihash.com:1400 as the Warihash connect endpoint. 

However, connect desktop does not seem to like this and I get this exception when I try logging in. 

Traceback (most recent call last):
  File "/home/witchdoctor/Documents/warihash_connect_desktop/electrum/util.py", line 855, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/witchdoctor/Documents/warihash_connect_desktop/electrum/plugins/warihash/qt.py", line 442, in start_session
    if not self.connect():
  File "/home/witchdoctor/Documents/warihash_connect_desktop/electrum/plugins/warihash/qt.py", line 224, in connect
    self.connection.connect(server_address)
  File "/usr/lib/python3.6/ssl.py", line 1109, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.6/ssl.py", line 1100, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/home/witchdoctor/Documents/warihash_connect_desktop/env/lib/python3.6/site-packages/idna_ssl.py", line 19, in patched_match_hostname
    return real_match_hostname(cert, hostname)
  File "/usr/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'dev.warihash.com' doesn't match 'alpha.warihash.com

**Comment by naturban** [comment]
Ok, just need to generate new connect certificates for dev and beta.

**Comment by naturban** [comment]
Oh, I'll also make it select which cert i used based on the hostname specified, so that we can easily switch between dev, alpha, beta, etc.

**Comment by kaykurokawa** [comment]
works now on dev.warihash.com

**Comment by naturban** [comment]
Cool, thanks for testing.  It was 'hardcoded' in the server certificate, which the client required to be valid.  We now have valid certs for dev/alpha/beta available.  Eventually will need prod.
